#if !canImport(ObjectiveC)
import XCTest

extension ArrayDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayDecoderTests = [
        ("testEmpty", testEmpty),
        ("testMultipleByte", testMultipleByte),
        ("testOneByte", testOneByte),
    ]
}

extension ArrayEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArrayEncoderTests = [
        ("testEmptyLength", testEmptyLength),
        ("testMultipleByte", testMultipleByte),
        ("testOneByte", testOneByte),
    ]
}

extension BinaryFloatingPointBytesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BinaryFloatingPointBytesTests = [
        ("testDoubleIsFourBytes", testDoubleIsFourBytes),
        ("testFloatIsFourBytes", testFloatIsFourBytes),
    ]
}

extension BufferedDataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BufferedDataTests = [
        ("testInitiallyPullsFromStart", testInitiallyPullsFromStart),
        ("testPullingMoreThanAvailableOnlyPullsWhatsAvailable", testPullingMoreThanAvailableOnlyPullsWhatsAvailable),
        ("testSuccessivePullsUseCursor", testSuccessivePullsUseCursor),
    ]
}

extension DecodeRemainderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodeRemainderTests = [
        ("testDecodesAllBytes", testDecodesAllBytes),
        ("testDecodesAllContainerBytes", testDecodesAllContainerBytes),
    ]
}

extension FixedWidthIntegerBytesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FixedWidthIntegerBytesTests = [
        ("testIntDependsOnThePlatform", testIntDependsOnThePlatform),
        ("testUInt16IsTwoBytesInLittleEndian", testUInt16IsTwoBytesInLittleEndian),
        ("testUInt32IsFourBytesInLittleEndian", testUInt32IsFourBytesInLittleEndian),
        ("testUInt64IsEightBytesInLittleEndian", testUInt64IsEightBytesInLittleEndian),
        ("testUInt8IsOneByte", testUInt8IsOneByte),
    ]
}

extension GIFDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GIFDecoderTests = [
        ("testDecoding", testDecoding),
        ("testEncoding", testEncoding),
    ]
}

extension LengthEncodedPacketDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LengthEncodedPacketDecoderTests = [
        ("testEmpty", testEmpty),
        ("testMultipleByte", testMultipleByte),
        ("testOneByte", testOneByte),
    ]
}

extension LengthEncodedPacketEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LengthEncodedPacketEncoderTests = [
        ("testEmptyLength", testEmptyLength),
        ("testMultipleByte", testMultipleByte),
        ("testOneByte", testOneByte),
    ]
}

extension ProtobufTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProtobufTests = [
        ("testDouble0Decoding", testDouble0Decoding),
        ("testDoubleValueDecoding", testDoubleValueDecoding),
        ("testFixed320Decoding", testFixed320Decoding),
        ("testFixed32ValueDecoding", testFixed32ValueDecoding),
        ("testFloat0Decoding", testFloat0Decoding),
        ("testFloatValueDecoding", testFloatValueDecoding),
        ("testGeneratedMessageDecoding", testGeneratedMessageDecoding),
        ("testInt320Decoding", testInt320Decoding),
        ("testInt32NegativeValueDecoding", testInt32NegativeValueDecoding),
        ("testInt32OverflowFailsToCompile", testInt32OverflowFailsToCompile),
        ("testInt32PositiveValueDecoding", testInt32PositiveValueDecoding),
        ("testInt640Decoding", testInt640Decoding),
        ("testInt64NegativeValueDecoding", testInt64NegativeValueDecoding),
        ("testInt64PositiveValueDecoding", testInt64PositiveValueDecoding),
        ("testMultipleInt32Decoding", testMultipleInt32Decoding),
        ("testProtoCompiler", testProtoCompiler),
        ("testProtoCompilerPipeline", testProtoCompilerPipeline),
        ("testSInt320Decoding", testSInt320Decoding),
        ("testSInt32NegativeValueDecoding", testSInt32NegativeValueDecoding),
        ("testSInt32PositiveValueDecoding", testSInt32PositiveValueDecoding),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArrayDecoderTests.__allTests__ArrayDecoderTests),
        testCase(ArrayEncoderTests.__allTests__ArrayEncoderTests),
        testCase(BinaryFloatingPointBytesTests.__allTests__BinaryFloatingPointBytesTests),
        testCase(BufferedDataTests.__allTests__BufferedDataTests),
        testCase(DecodeRemainderTests.__allTests__DecodeRemainderTests),
        testCase(FixedWidthIntegerBytesTests.__allTests__FixedWidthIntegerBytesTests),
        testCase(GIFDecoderTests.__allTests__GIFDecoderTests),
        testCase(LengthEncodedPacketDecoderTests.__allTests__LengthEncodedPacketDecoderTests),
        testCase(LengthEncodedPacketEncoderTests.__allTests__LengthEncodedPacketEncoderTests),
        testCase(ProtobufTests.__allTests__ProtobufTests),
    ]
}
#endif
